### ISSUE TITLE
Add Dark Mode to the Interactive Demo Site

### ISSUE THREAD

**Issue by princefishthrower** [princefishthrower/react-use-please-stay#4]
Just a fun one, and perfect for the October season (at least for those of us in the northern hemisphere 😉 ). I'd like to add a dark mode toggler to the [interact demo site](https://princefishthrower.github.io/react-use-please-stay/)!

This would include:
- Adding a header component to the demo site
- Adding a toggle button to switch from dark to light modes
- This toggler should detect the preferred mode automatically - not sure if this one is even possible, we have to look - at the very least the preference should be saved in a cookie when toggled

**Comment by babu1998** [comment]
@princefishthrower I would like to take this up.

**Comment by princefishthrower** [comment]
@babu1998 go for it! I've assigned you to this issue.

**Comment by babu1998** [comment]
to clarify I have to add the toggle button in the header component?

**Comment by princefishthrower** [comment]
Yes, my hope was that part of this pull request a header would be added to the interactive demo site, since there isn't one yet. I may add another issue later to add things to this header, like a link to github etc

**Comment by camperjett** [comment]
Is it necessary to get assigned to this issue in order to create a pr?

**Comment by babu1998** [comment]
I am working on this @camperjett

**Comment by babu1998** [comment]
I have made the changes but facing problem to push my branch

remote: Permission to princefishthrower/react-use-please-stay.git denied to babu1998.

**Comment by princefishthrower** [comment]
@camperjett - assignment isn't needed to create a PR technically, but I'll be taking the PR from @babu1998 since I think a first come first serve process is the only fair way here.

**Comment by princefishthrower** [comment]
@babu1998 - I left a small change request on your PR.
